name: "Prebuild Dev Container"
on:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prebuild:
    name: Prebuild
    runs-on: ubuntu-latest
    permissions:
      contents: read # checkout the repo
      packages: write # publish features to GHCR
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Log in to GHCR
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Pre-build dev container image
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          imageName: ghcr.io/trevorlauder/devcontainer
          cacheFrom: type=registry,ref=ghcr.io/trevorlauder/devcontainer:buildcache
          cacheTo: type=registry,ref=ghcr.io/trevorlauder/devcontainer:buildcache,mode=max
          platform: linux/arm64
          push: always
